baseapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include, reverse_lazy
from django.views.generic import TemplateView, RedirectView
# from .views import HomeView
from .views import InterestsView, RememberLoginView, SignUpView, EditInterested
from .forms import RememberAuthForm

urlpatterns = [
    path('', RedirectView.as_view(url=reverse_lazy('self_interests')), name='home'),
    path('interests/', InterestsView.as_view(), name='self_interests'),
    path('interests/<str:username>', InterestsView.as_view(), name='interests'),
    path('login/', RememberLoginView.as_view(form_class=RememberAuthForm, redirect_authenticated_user=True), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('edit_interested/', EditInterested.as_view(), name='edit_interested')
]

favorite/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baseapp.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baseapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from favorite.settings import DEBUG

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars', default='/default/user.png')
    about_me = models.TextField(max_length=280)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        if not DEBUG and not instance.is_staff:
            instance.is_active = False
            instance.save()
            #Implemet send email to activate account





@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Interest(models.Model):
    creator = models.ForeignKey(User, blank=True, null=True, db_index=True, on_delete=models.SET_NULL)
    user_interested = models.ManyToManyField(User, through='Interested', related_name='interests', blank=True)
    name = models.CharField(max_length=255)
    thumbnail = models.ImageField(upload_to='interest_images', default='/default/thinking_emoji.png')
    INTEREST_TYPES = (
        ('M', 'Movie'),
        ('A', 'Anime'),
        ('B', 'Book'),
        ('G', 'Games'),
        ('S', 'Series'),
        ('O', 'Other')
    )
    interest_type = models.CharField(max_length=1, choices=INTEREST_TYPES)

    def full_type(self):
        return dict(Interest.INTEREST_TYPES)[self.interest_type]

    def search_link(self):
        engines = {
            'A': 'https://myanimelist.net/anime.php?q=',
        }
        url = engines.get(self.interest_type, '')
        if url:
            url += self.name
        return url

    def __str__(self):
        return f'({self.interest_type}) {self.name}'


class Interested(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    interest = models.ForeignKey(Interest, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)
    super_like = models.BooleanField(default=False)
    note = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['-super_like']
        unique_together = ('user', 'interest')

    def __str__(self):
        return f'{self.user} - {self.interest.name}  {"+++" if self.super_like else ""}'

baseapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django import forms

from baseapp.models import Interest, Interested, User

class RememberAuthForm(AuthenticationForm):
    remember_me = forms.BooleanField(label="Don't remember me", required=False)


class EmailUserCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class InterestForm(forms.ModelForm):
    note = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Interest
        exclude = ['user_interested', 'thumbnail', 'creator']
        # widgets = {'user_interested': forms.HiddenInput()}
    #
    # def save(self, user=None, *args, **kwargs):
    #     instance = super(InterestForm, self).save(commit=False, *args, **kwargs)
    #     instance.creator = user
    #     instance.save()
    #     return instance

baseapp/views.py
from django.contrib.auth import get_user_model, login, authenticate
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.sites.shortcuts import get_current_site

from baseapp.models import Interested, Interest
from .forms import EmailUserCreationForm, InterestForm
# Create your views here.
from django.views.generic.base import View

User = get_user_model()



class InterestsView(View):
    def get(self, request, username=None):
        user = request.user
        if username:
            owner = get_object_or_404(User, username=username)
        elif not user.is_authenticated:
            return redirect('login')
        else:
            owner = user
        can_modify = False

        # if user.is_authenticated or True:
        #    print(request.session.get_expiry_age())

        if user.pk == owner.pk:
            can_modify = True

        context = {
            'owner': owner,
            'can_modify': can_modify,
        }

        if can_modify:
            addform = InterestForm()
            context['addform'] = addform

        return render(request, 'baseapp/interests.html', context)

    def post(self, request):

        user = request.user
        addedform = InterestForm(request.POST, request.FILES)
        if addedform.is_valid():
            interest_name = addedform.cleaned_data['name']
            interest_type = addedform.cleaned_data['interest_type']
            try:
                interest = Interest.objects.get(name=interest_name, interest_type=interest_type)
            except Interest.DoesNotExist:
                interest = Interest.objects.create(
                    creator=request.user,
                    name=interest_name,
                    interest_type=interest_type)

            try:
                interested = Interested.objects.get(user=user, interest=interest)
            except Interested.DoesNotExist:
                interested = Interested()
                interested.user = user
                interested.interest = interest
                interested.note = request.POST['note']
                interested.save(user)
        else:
            print(addedform.errors)

        return redirect('self_interests')


class RememberLoginView(LoginView):
    def form_valid(self, form):
        if self.request.POST.get('remember_me', False):  # don't remember me I am sorry
            self.request.session.set_expiry(60 * 60 * 1)
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())


class SignUpView(View):
    def get(self, request):
        context = {
            "form": EmailUserCreationForm,
        }

        return render(request, 'registration/signup.html', context)

    def post(self, request):
        form = EmailUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
        else:
            context = {
                "form": form,
            }
        return render(request, 'registration/signup.html', context)


class EditInterested(View):
    def post(self, request):
        operation = request.POST.get('operation')
        pk = request.POST.get('pk')
        try:
            interested = Interested.objects.get(pk=pk)
        except Interested.DoesNotExist:
            return JsonResponse({'success': False, 'errorMsg': 'Bad pk or previously deleted!'})

        if request.user == interested.user:
            if operation == 'super_like':
                interested.super_like = not interested.super_like
                interested.save()
                return JsonResponse({'success': True})

            if operation == 'delete':
                interested.delete()
                return JsonResponse({'success': True})

baseapp/templates/baseapp/add_interest.html
    {% extends 'baseapp/base.html' %}
    {% load static %}
    {% block header %}
    <script src="{% static "jquery.easy-autocomplete.js" %}"></script>
    <link rel="stylesheet" href="{% static "easy-autocomplete.css" %}">
    <link rel="stylesheet" href="{% static "easy-autocomplete.themes.css" %}">
    {% endblock %}


{% block content %}
<div class="container">
    <input id="anime-input"/>
    <script>
        let options = {
            url: "{% static "animes.json" %}",
            getValue: "name",
            list: {
                match: {
                    enabled: true
                }
            },

            template: {
                type: "iconLeft",
                fields: {
                    iconSrc: "thumbnail"
                }
            },

            theme: "square"
        };
        $("#anime-input").easyAutocomplete(options);
    </script>
</div>
{% endblock %}

baseapp/templates/baseapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
          integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>

    {% block header %}

    {% endblock %}

    <style>
        body {
            background-color: #f5f8fa;
        }

        .navbar {
            background-color: #10BBB3;
        }

        .text-light-blue {
            color: #10BBB3 !important;
        }


    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light">

    <div class="d-flex align-items-center text-white" href="#">
        {{ request.user.username }}
        <img src="{{ request.user.profile.avatar.url }}" width="50" height="50"
             class="d-inline-block align-top" alt="">
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="text-white navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <!--<a class="navbar-brand ml-auto" href="#">Hidden brand</a>-->
        <ul class="navbar-nav ml-auto">
            {% if not request.user.is_authenticated %}

                <li class="nav-item active">
                    <a class="nav-link text-white" href="{% url 'signup' %}">Register</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link text-white" href="{% url 'login' %}">Login</a>
                </li>

            {% endif %}
            <li class="nav-item active">
                <a class="nav-link text-white" href="{% url 'login' %}">About Us</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link text-white" href="{% url 'login' %}">Contact Us</a>
            </li>

            {% if request.user.is_authenticated %}
                <li class="nav-item text-white">
                    <a class="nav-link text-white" href="{% url 'logout' %}">Logout</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

{% block user_info %}
    <div class="container">
        <div class="row">
            <div class="col-12 bg-white p-2 rounded mt-2">
                <div class="d-flex justify-content-center text-center">
                    <ul class="list-unstyled">
                        <li><img class="rounded-circle" src="{{ owner.profile.avatar.url }}" width="150" height="150"
                                 alt="profile_picture"></li>
                        <li class="pt-2"><h6>{{ owner.username }}</h6></li>
                        <li><span>{{ owner.profile.about_me }}</span></li>
                        <li><span><a href="{{ request.get_full_path }}">Link to here</a></span></li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
{% endblock %}


{% block content %}

{% endblock %}


<script>
    $('tr[rel=popover]').popover({
        html: true,
        trigger: 'hover',
        placement: 'bottom',
        content: function () {
            return '<img height="250" src="' + $(this).data('img') + '" />';
        }
    });

</script>
</body>
</html>

baseapp/templates/baseapp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Favorite</title>
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <!-- JS file -->
    <script src="{% static "jquery.easy-autocomplete.js" %}"></script>
    <!-- CSS file -->
    <link rel="stylesheet" href="{% static "easy-autocomplete.css" %}">
    <!-- Additional CSS Themes file - not required-->
    <link rel="stylesheet" href="{% static "easy-autocomplete.themes.css" %}">
</head>
<body>


<div id="opa">
    opa

    <input id="anime-input"/>
    <script>
        let options = {
            url: "{% static "animes.json" %}",
            getValue: "name",
            list: {
                match: {
                    enabled: true
                }
            },

            template: {
                type: "iconLeft",
                fields: {
                    iconSrc: "thumbnail"
                }
            },

            theme: "square"
        };


        $("#anime-input").easyAutocomplete(options);


    </script>

</div>

</body>
</html>

baseapp/templates/baseapp/interests.html
{% extends 'baseapp/base.html' %}
{% load static %}
{% block header %}
    <script src="{% static "jquery.easy-autocomplete.js" %}"></script>
    <link rel="stylesheet" href="{% static "easy-autocomplete.css" %}">
    <link rel="stylesheet" href="{% static "easy-autocomplete.themes.css" %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 interests m-3 text-center">
                <div class="row align-items-center justify-content-center">
                    <h2>Interests</h2>
                    <i class="fa fa-search ml-2"></i>
                </div>
                <div class="row btn-group-toggle">
                    <div class="col-2 btn btn-outline-info">Movies</div>
                    <div class="col-2 btn btn-outline-info">Series</div>
                    <div class="col-2 btn btn-outline-info">Anime</div>
                    <div class="col-2 btn btn-outline-info">Books</div>
                    <div class="col-2 btn btn-outline-info">Games</div>
                    <div class="col-2 btn btn-outline-info">Others</div>
                </div>

                <table class="table table-striped mt-2">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Type</th>
                        <th scope="col"></th>
                        <th scope="col">Name</th>
                        <th scope="col"></th>
                        <th scope="col">Note</th>

                    </tr>
                    </thead>

                    <tbody>
                    {% if can_modify %}
                        <tr>
                            <td colspan="6" class="btn-info" style="cursor:pointer" data-toggle="modal"
                                data-target="#addinterest">Add new interest
                            </td>
                        </tr>
                    {% endif %}

                    {% for interested in owner.interested_set.all %}
                        <tr id="interested{{ interested.pk }}" rel="popover" data-img="{{ interested.interest.thumbnail.url }}">
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ interested.interest.full_type }}</td>
                            <td>
                                <span id="like{{ interested.pk }}" style="cursor:pointer">
                                {% if interested.super_like %}
                                    <i class="fas fa-star" onclick=superLike({{ interested.pk }})></i>
                                {% else %}
                                    <i class="far fa-star" onclick=superLike({{ interested.pk }})></i>
                                {% endif %}
                                </span>

                            </td>

                            <td>{{ interested.interest.name }}
                                {% if interested.interest.search_link %}
                                    <a title="Open help" target="_blank" href="{{ interested.interest.search_link }}">
                                        <i class="fas fa-info-circle"></i>
                                    </a>
                                {% endif %}
                            </td>


                            <td>
                                <i title="Copy to my list" class="fas fa-copy"></i>
                                {% if can_modify %}
                                    <i class="fas fa-edit"></i>
                                    <i class="fas fa-trash-alt" style="cursor:pointer" onclick=delInterested({{ interested.pk }})></i>
                                {% endif %}

                            </td>
                            <td><span class="text-info" style="cursor:pointer" data-toggle="modal"
                                      data-target="#note{{ forloop.counter }}">{{ interested.note|truncatechars:40 }}</span>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    {% for interested in owner.interested_set.all %}

        <div class="modal fade" id="note{{ forloop.counter }}" tabindex="-1" role="dialog"
             aria-labelledby="exampleModalLongTitle"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {{ interested.note }}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

    {% endfor %}
    {% if can_modify %}
        <div class="modal fade" id="addinterest" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <form action="{% url 'self_interests' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="modal-body">
                            {{ addform.as_ul }}
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Add</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </form>


                </div>
            </div>
        </div>
    {% endif %}

    <script>
        let options = {
            url: "{% static "animes.json" %}",
            getValue: "name",
            list: {
                match: {
                    enabled: true
                }
            },

            template: {
                type: "iconLeft",
                fields: {
                    iconSrc: "thumbnail"
                }
            },

            //theme: "square"
        };
        $("#id_name").easyAutocomplete(options);

        function superLike(pk){
            $.post({
                url: "{% url 'edit_interested' %}",
                data: {
                    pk: pk,
                    operation: 'super_like',
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function (data) {
                    $("#like" + pk).children('i').toggleClass('fas far')
                    //.addClass('fa-star')
                }
        })}

        function delInterested(pk){
            $.post({
                url: "{% url 'edit_interested' %}",
                data: {
                    pk: pk,
                    operation: 'delete',
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function (data) {
                    $("#interested" + pk).hide();

                }
        })}
    
    </script>


{% endblock %}